DELIMITER $$
DROP PROCEDURE IF EXISTS `insert_food_items`$$
CREATE PROCEDURE `insert_food_items`(lid INT,lfood_id TINYINT,lquantity INT)
BEGIN
INSERT INTO ORDER_FOOD_MAINTENANCE (ORDER_ID,FOOD_ID,QUANTITY)
VALUES (lid,lfood_id,lquantity);
END$$
DELIMITER ;