DELIMITER $$
DROP PROCEDURE IF EXISTS `update_price`$$
CREATE PROCEDURE `update_price`(lid INT)
BEGIN
UPDATE ORDERS 
	SET TOTAL_PRICE=(
	SELECT SUM(TOTAL_PRICE)
	FROM ORDER_FOOD_MAINTENANCE WHERE ORDER_ID=lid AND STATUS='Ordered' GROUP BY ORDER_ID) 
	WHERE ID=lid;
END$$
DELIMITER ;