DELIMITER $$
DROP PROCEDURE IF EXISTS `update_price`$$
CREATE PROCEDURE `update_price`(lid INT)
BEGIN
	UPDATE ORDERS 
		SET TOTAL_PRICE=(
			SELECT SUM(PRICE*QUANTITY)FROM SEED_FOOD
			JOIN ORDER_FOOD_MAINTENANCE
			ON SEED_FOOD.ID=ORDER_FOOD_MAINTENANCE.FOOD_ID
			WHERE ORDER_FOOD_MAINTENANCE.ORDER_ID=lid
			AND ORDER_FOOD_MAINTENANCE.STATUS<>'Cancelled'
			GROUP BY ORDER_FOOD_MAINTENANCE.ORDER_ID)
		WHERE ORDERS.ID=lid;
END$$
DELIMITER ;