CREATE VIEW STOCKS_REMAINING 
AS
	SELECT FSM.`FOOD_ID`,SF.`NAME`AS NAME,SS.`NAME` AS SESSION, 
       IFNULL(FSM.`QUANTITY`-SUM(OFM.QUANTITY),FSM.`QUANTITY`) AS REMAINING_QUANTITY
FROM food_session_maintenance FSM
LEFT JOIN SEED_FOOD SF
ON FSM.`FOOD_ID`=SF.`ID`
LEFT JOIN SEED_SESSION SS
ON FSM.`SESSION_ID`=SS.`ID`
LEFT JOIN order_food_maintenance OFM
ON FSM.`FOOD_ID`=OFM.`FOOD_ID`
AND EXISTS 
		( SELECT 1 FROM SEED_SESSION WHERE ID = SS.ID AND TIME(OFM.`ORDERED_TIME`) BETWEEN START_TIME AND END_TIME )
	AND DATE(OFM.`ORDERED_TIME`)=CURDATE()
	AND OFM.`STATUS`<>'Cancelled'
	GROUP BY FSM.`FOOD_ID`,FSM.`SESSION_ID`
	ORDER BY FSM.`SESSION_ID` ASC,FSM.`FOOD_ID` ASC;