CREATE VIEW MENU AS
SELECT SEED_FOOD.NAME AS NAME,SEED_FOOD.PRICE AS PRICE,SEED_SESSION.NAME  AS SESSION 
FROM  FOOD_SESSION_MAINTENANCE
JOIN SEED_FOOD
	ON FOOD_SESSION_MAINTENANCE.FOOD_ID=SEED_FOOD.ID
JOIN SEED_SESSION
	ON FOOD_SESSION_MAINTENANCE.SESSION_ID=SEED_SESSION.ID
ORDER BY SEED_SESSION.ID;  