DELIMITER $$
DROP FUNCTION IF EXISTS `isfood_ordered`$$
CREATE FUNCTION `isfood_ordered`(lseat_number TINYINT,lfood_id TINYINT) RETURNS TINYINT(1)
BEGIN
DECLARE result BOOLEAN DEFAULT FALSE;
IF (EXISTS(SELECT ORDER_FOOD_MAINTENANCE.FOOD_ID FROM ORDER_FOOD_MAINTENANCE
		JOIN ORDERS
		ON ORDER_FOOD_MAINTENANCE.ORDER_ID=ORDERS.ID 
		WHERE ORDERS.SEAT_NUMBER=lseat_number
			AND ORDER_FOOD_MAINTENANCE.FOOD_ID=lfood_id 
			 AND ORDER_FOOD_MAINTENANCE.STATUS='Ordered')) THEN
SET result=TRUE;
END IF;
RETURN result;
END$$
DELIMITER ;