DELIMITER $$
DROP FUNCTION IF EXISTS `isfood_available`$$
CREATE FUNCTION `isfood_available`(lfood_id TINYINT) RETURNS TINYINT(1)
BEGIN
DECLARE result BOOLEAN DEFAULT FALSE;
DECLARE stocks_sold INT DEFAULT 0;
SELECT SUM(ORDER_FOOD_MAINTENANCE.QUANTITY) INTO stocks_sold FROM ORDER_FOOD_MAINTENANCE 
JOIN ORDERS
ON ORDER_FOOD_MAINTENANCE.ORDER_ID=ORDERS.ID
WHERE FOOD_ID=lfood_id AND DATE(ORDER_FOOD_MAINTENANCE.ORDERED_TIME)=CURRENT_DATE AND ORDER_FOOD_MAINTENANCE.STATUS<>'Cancelled'
GROUP BY(ORDER_FOOD_MAINTENANCE.FOOD_ID);
IF ((SELECT QUANTITY FROM FOOD_SESSION_MAINTENANCE WHERE FOOD_ID=lfood_id
AND SESSION_ID IN(SELECT ID FROM SEED_SESSION WHERE CURRENT_TIME BETWEEN START_TIME AND END_TIME)
)>stocks_sold)THEN
SET result=TRUE;
END IF;
RETURN result;
END$$
DELIMITER ;