DELIMITER $$
DROP FUNCTION IF EXISTS `isitem_present`$$
CREATE FUNCTION `isitem_present`(litem_name VARCHAR(30)) 
RETURNS BOOLEAN
BEGIN
DECLARE result BOOLEAN DEFAULT FALSE;
/* checking whether valid food name and 
checking whether food is in the current session */
IF (EXISTS(SELECT NAME FROM SEED_FOOD WHERE NAME=litem_name) AND 
EXISTS
(SELECT NAME FROM SEED_FOOD WHERE ID IN (
SELECT FOOD_ID FROM FOOD_SESSION_MAINTENANCE WHERE SESSION_ID IN(
SELECT ID FROM SEED_SESSION WHERE CURRENT_TIME BETWEEN START_TIME AND END_TIME)
))
) THEN
SET result=TRUE;
END IF;
RETURN result;
END$$
DELIMITER ;